import { NextRequest, NextResponse } from "next/server";
import ZAI from "z-ai-web-dev-sdk";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SYSTEM_PREAMBLE = `You are T³'s Generative UIX Agent for the Android phone shell. The user is in Strict Sandbox mode, so the entire home screen / status bar / app drawer / quick settings / navigation bar are generated by you.

Produce a complete AndroidUixManifest as a single JSON object (no prose, no markdown fences) matching this schema exactly:

{
  "vibe": "<short echo of the user's vibe, max 8 words>",
  "wallpaper": {
    "type": "GRADIENT" | "MESH" | "SOLID",
    "colors": ["#RRGGBB", "#RRGGBB", "#RRGGBB", "#RRGGBB"],
    "overlayAlpha": 0.18
  },
  "accent": "#RRGGBB",
  "accentSecondary": "#RRGGBB",
  "statusBar": {
    "style": "LIGHT" | "DARK" | "TRANSLUCENT",
    "tint": "#RRGGBB",
    "showCarrier": true,
    "carrierLabel": "T³ Mobile"
  },
  "home": {
    "gridStyle": "GRID_5" | "GRID_4" | "LIST" | "COMPACT_6",
    "columns": 5,
    "iconShape": "CIRCLE" | "SQUIRCLE" | "ROUNDED" | "PEBBLE",
    "iconSize": 56,
    "labelColor": "#RRGGBB",
    "showLabels": true,
    "pageIndicators": true
  },
  "dock": {
    "enabled": true,
    "apps": ["Phone", "Messages", "Chrome", "Camera", "T³ Console"],
    "background": "#66FFFFFF"
  },
  "appDrawer": {
    "sort": "ALPHABETICAL" | "RECENT" | "MOST_USED",
    "searchBar": true,
    "background": "#E6F0FA"
  },
  "navBar": {
    "style": "GESTURE" | "THREE_BUTTON",
    "accent": "#RRGGBB"
  },
  "quickSettings": {
    "tiles": [
      { "id": "wifi", "label": "Wi-Fi", "icon": "Wifi", "active": true }
    ]
  },
  "notifications": [
    {
      "id": "n1",
      "appPackage": "com.google.android.gm",
      "appName": "Gmail",
      "title": "T³ Team",
      "body": "Welcome to your generative phone UIX.",
      "iconGradient": ["#EA4335", "#FBBC04"],
      "timestamp": 0,
      "priority": "DEFAULT"
    }
  ],
  "fontScale": 1.0,
  "cornerRadius": 28,
  "weather": {
    "tempF": 68,
    "condition": "Sunny",
    "location": "San Francisco",
    "icon": "Sun",
    "highF": 72,
    "lowF": 58
  }
}

Rules:
1. Honor the user's vibe. Examples:
   - "neon cyberpunk" → dark MESH wallpaper, vibrant cyan/magenta accent, COMPACT_6 grid, SQUIRCLE icons, TRANSLUCENT status bar.
   - "calm zen garden" → light GRADIENT wallpaper, muted sage accent, GRID_5, CIRCLE icons, LIGHT status bar.
   - "retro 80s sunset" → warm MESH wallpaper, coral/gold accent, GRID_4, ROUNDED icons, TRANSLUCENT status bar.
   - "minimal stock android" → light GRADIENT, blue accent, GRID_5, CIRCLE icons, LIGHT status bar.
2. quickSettings.tiles must contain exactly 6 tiles, each with a valid icon token from this whitelist: "Wifi", "Bluetooth", "Moon", "Flashlight", "Plane", "RotateCw", "Battery", "Signal", "RadioTower", "Gauge".
3. dock.apps must contain exactly 5 strings, drawn from this allowed list: "Phone", "Messages", "Chrome", "Camera", "T³ Console", "Maps", "YouTube", "Gmail", "Photos", "Calendar".
4. notifications must contain 1–3 items. Make them feel on-theme and useful (a system update, a synced tab, a calendar event). Set iconGradient to two hex colors that match the app.
5. All colors are 6-digit hex #RRGGBB. dock.background and appDrawer.background and notifications.iconGradient may use 8-digit hex with alpha.
6. fontScale between 0.85 and 1.2. cornerRadius between 8 and 48.
7. weather.icon must be one of: "Sun", "Cloud", "CloudRain", "CloudSnow", "CloudSun". Match the weather to the vibe (e.g. "aurora borealis" → "CloudSnow", "cyberpunk" → "Cloud", "zen garden" → "Sun").
8. Respond with ONLY the JSON object. No prose, no fences, no explanation.`;

export async function POST(req: NextRequest) {
  try {
    const { vibe, deviceState } = await req.json();
    if (!vibe || typeof vibe !== "string") {
      return NextResponse.json({ error: "vibe required" }, { status: 400 });
    }

    const zai = await ZAI.create();
    const completion = await zai.chat.completions.create({
      messages: [
        { role: "assistant", content: SYSTEM_PREAMBLE },
        {
          role: "user",
          content: `Device state: ${JSON.stringify(deviceState ?? {})}\nUser vibe: "${vibe}"`,
        },
      ],
      thinking: { type: "disabled" },
    });

    const raw = completion.choices[0]?.message?.content ?? "";
    const cleaned = raw.replace(/```json\s*/gi, "").replace(/```\s*$/i, "").trim();
    let manifest: unknown = null;
    try {
      manifest = JSON.parse(cleaned);
    } catch {
      const m = cleaned.match(/\{[\s\S]*\}/);
      if (m) {
        try {
          manifest = JSON.parse(m[0]);
        } catch {
          manifest = null;
        }
      }
    }
    return NextResponse.json({ manifest, raw });
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ error: message, manifest: null }, { status: 200 });
  }
}
